// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPCa1vFhTYpXxPQQCbmEIbtmCClaHzC5U',
    appId: '1:318140309920:web:37af3e371ffd81341b84c5',
    messagingSenderId: '318140309920',
    projectId: 'anglais-12976',
    authDomain: 'anglais-12976.firebaseapp.com',
    storageBucket: 'anglais-12976.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzRrg22MZu-UezR7ixgPJZCzxksTq-clA',
    appId: '1:318140309920:android:1bfef56bb08005b11b84c5',
    messagingSenderId: '318140309920',
    projectId: 'anglais-12976',
    storageBucket: 'anglais-12976.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA39Ui1Zu2DfSDKrln0PprDWVdlXp2y5LI',
    appId: '1:318140309920:ios:a54cd64b53be6ff71b84c5',
    messagingSenderId: '318140309920',
    projectId: 'anglais-12976',
    storageBucket: 'anglais-12976.firebasestorage.app',
    iosBundleId: 'com.example.flutterAnglais',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA39Ui1Zu2DfSDKrln0PprDWVdlXp2y5LI',
    appId: '1:318140309920:ios:a54cd64b53be6ff71b84c5',
    messagingSenderId: '318140309920',
    projectId: 'anglais-12976',
    storageBucket: 'anglais-12976.firebasestorage.app',
    iosBundleId: 'com.example.flutterAnglais',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPCa1vFhTYpXxPQQCbmEIbtmCClaHzC5U',
    appId: '1:318140309920:web:6d6f85fc8be28d061b84c5',
    messagingSenderId: '318140309920',
    projectId: 'anglais-12976',
    authDomain: 'anglais-12976.firebaseapp.com',
    storageBucket: 'anglais-12976.firebasestorage.app',
  );
}
